### ISSUE TITLE
Handle to scan manifest file not being released after exiting on Windows

### ISSUE THREAD

**Issue by melotic** [microsoft/component-detection#681]
It seems that on Windows we're running into race conditions where a previous invocation of CD doesn't release the handle to the manifest. Running another CD scan will fail if we try to output to the same manifest file from the first invocation.

[Example Build](https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=20825624&view=logs&j=3767afc8-581c-5035-b164-b3f396e67d13&t=3ea3d2e0-c830-57f2-1f88-597cee541063)

```
System.IO.IOException: The process cannot access the file 'D:\a\1\a\bcde-output\bcde-output.json' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String ***h, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String ***h, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String ***h, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String ***h)
   at Microsoft.ComponentDetection.Common.FileWritingService.WriteFile[T](FileInfo relativeFilePath, T obj)
   at Microsoft.ComponentDetection.Orchestrator.Services.BcdeScanCommandService.WriteComponentManifest(IDetectionArguments detectionArguments, ScanResult scanResult)
   at Microsoft.ComponentDetection.Orchestrator.Services.BcdeScanCommandService.HandleAsync(IScanArguments arguments)
   at Microsoft.ComponentDetection.Internal.AzureDevOps.Services.BcdeWrapperService.ExecuteScanAsync(DetectionArguments detectionArguments) in /home/runner/work/component-detection-internal/component-detection-internal/ComponentDetection/src/Microsoft.ComponentDetection.Internal.Orchestrator/Services/BcdeWrapperService.cs:line 64
   at Microsoft.ComponentDetection.Internal.AzureDevOps.Services.ComponentDetectionCommandService.HandleAsync(IComponentDetectionArguments inputArguments) in /home/runner/work/component-detection-internal/component-detection-internal/ComponentDetection/src/Microsoft.ComponentDetection.Internal.Orchestrator/Services/ComponentDetectionCommandService.cs:line 114
```

AB#2087245

**Comment by cobya** [comment]
Manifest writing functionality has been updated a few times since this issue was opened and I haven't seen a repro recently. Closing this, but feel free to reopen if you see the same issue again.
