### ISSUE TITLE
Add support for using as a library

### ISSUE THREAD

**Issue by edena-legit** [microsoft/component-detection#728]
Hi 👋 
Currently, it seems that the only way to use this tool is by command line.
It seems that the DI registration is using `AsSingleton` for all the components and not a scoped instance, leading to errors between calls because of the states the detectors are using. 
It will be very appreciated if docs on how to use this tool as a library will be added (as it states in the README.md that it could)

**Comment by melotic** [comment]
Hi,

CD is supported as using a library. You'd have to use DI to resolve a `IBcdeScanExecutionService` and run `ExecuteScanAsync`.

You can use the extension method `AddComponentDetection` to your `ServiceCollection` to register all dependencies.

https://github.com/microsoft/component-detection/blob/74fae320e190d2d01a780bf0f1e1f8428029f846/src/Microsoft.ComponentDetection.Orchestrator/Extensions/ServiceCollectionExtensions.cs#L41

>It seems that the DI registration is using AsSingleton for all the components and not a scoped instance, leading to errors between calls because of the states the detectors are using.

Can you share the exact error?

**Comment by edena-legit** [comment]
Seems like there a detectors that holds state which leads to errors between calling such as:
` ---> System.ArgumentException: An item with the same key has already been added. Key: OmittedFrameworkComponents
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.ComponentDetection.Detectors.NuGet.NuGetProjectModelProjectCentricComponentDetector.OnDetectionFinishedAsync()
   at Microsoft.ComponentDetection.Contracts.FileComponentDetector.ProcessAsync(IObservable`1 processRequests, IDictionary`2 detectorArgs)
   at Microsoft.ComponentDetection.Contracts.FileComponentDetector.ExecuteDetectorAsync(ScanRequest request)
   at Microsoft.ComponentDetection.Orchestrator.Services.DetectorProcessingService.WithExperimentalScanGuardsAsync(Func`1 detectionTaskGenerator, Boolean isExperimentalDetector, DetectorExecutionTelemetryRecord telemetryRecord)
   at Microsoft.ComponentDetection.Orchestrator.Services.DetectorProcessingService.<>c__DisplayClass4_0.<<ProcessDetectorsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.ComponentDetection.Orchestrator.Services.DetectorProcessingService.ProcessDetectorsAsync(IDetectionArguments detectionArguments, IEnumerable`1 detectors, DetectorRestrictions detectorRestrictions)
   at Microsoft.ComponentDetection.Orchestrator.Services.BcdeScanExecutionService.ExecuteScanAsync(IDetectionArguments detectionArguments)
   at Scanners.Dependencies.Scanners.ComponentDetectionScanner.ScanAsync(StorageRepositoryUpdated repositoryUpdated) in /Users/edena/RiderProjects/code-scanners-service/src/Scanners/Dependencies/Scanners/ComponentDetectionScanner.cs:line 151
   --- End of inner exception stack trace ---
   at Scanners.Dependencies.Scanners.ComponentDetectionScanner.ScanAsync(StorageRepositoryUpdated repositoryUpdated) in /Users/edena/RiderProjects/code-scanners-service/src/Scanners/Dependencies/Scanners/ComponentDetectionScanner.cs:line 188`

**Comment by edena-legit** [comment]
I'm receiving the following error as well: 
```
Base path has not yet been initialized in File Writing Service! Microsoft.ComponentDetection.Commonexception.StackTraceString: at Microsoft.ComponentDetection.Common.FileWritingService.EnsureInit()
at Microsoft.ComponentDetection.Common.FileWritingService.ResolveFilePath(String relativeFilePath)
at Microsoft.ComponentDetection.Orchestrator.Experiments.DefaultExperimentProcessor.ProcessExperimentAsync(IExperimentConfiguration config, ExperimentDiff diff)
at Microsoft.ComponentDetection.Orchestrator.Experiments.ExperimentService.FinishAsync()
```

Running as a library, I don't expect the file-writing service to do anything, right?

**Comment by edena-legit** [comment]
@melotic, Anything on that?

**Comment by melotic** [comment]
> I'm receiving the following error as well:
> 
> ```
> Base path has not yet been initialized in File Writing Service! 
> 
> Microsoft.ComponentDetection.Commonexception.StackTraceString: 
> at Microsoft.ComponentDetection.Common.FileWritingService.EnsureInit()
> at Microsoft.ComponentDetection.Common.FileWritingService.ResolveFilePath(String relativeFilePath)
> at Microsoft.ComponentDetection.Orchestrator.Experiments.DefaultExperimentProcessor.ProcessExperimentAsync(IExperimentConfiguration config, ExperimentDiff diff)
> at Microsoft.ComponentDetection.Orchestrator.Experiments.ExperimentService.FinishAsync()
> ```
> 
> Running as a library, I don't expect the file-writing service to do anything, right?

Call `Init` in the file writer service, or register a service that does nothing. 

https://github.com/microsoft/component-detection/blob/2b86e05499f96f9202c8e866c7e95e08fa37fa9e/src/Microsoft.ComponentDetection.Orchestrator/Orchestrator.cs#L165
